# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Rest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_c8de239c6b3149b99bd4a5e6553472a4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_63c9ff71e0cd4756a352e673ea75db37 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_c8de239c6b3149b99bd4a5e6553472a4 }}/rest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Rest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ef25931aa43a45ea8206e462de2f8f45 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_c8de239c6b3149b99bd4a5e6553472a4 }}/rest:${{ github.sha }}'